# Generated by Django 5.0.3 on 2024-03-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payementrecipe',
            name='recipe_type',
            field=models.CharField(choices=[('client', 'Client'), ('bank', 'Bank')], default='client', max_length=30),
        ),
    ]
