from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="home"),
    path('statistics', views.statistics, name="statistics"),
    path('about', views.about, name="about"),
    path('category/algeria_bank', views.algeria_bank, name="algeria_bank"),
    path('category/banking_laws', views.banking_laws, name="banking_laws"),
    path('category/banking_services',
         views.banking_services, name="banking_services"),
    path('category/banks_list', views.banks_list, name="banks_list"),
    path('category/deposits', views.deposits, name="deposits"),
    path('category/electronic_banking',
         views.electronic_banking, name="electronic_banking"),
    path('category/fiscal_policy', views.fiscal_policy, name="fiscal_policy"),
    path('category/general_info', views.general_info, name="general_info"),
    path('category/islamic_banking', views.islamic_banking, name="islamic_banking"),
    path('category/loan_calculator', views.loan_calculator, name="loan_calculator"),
    path('category/loans', views.loans, name="loans"),
    path('category/monetary_policy', views.monetary_policy, name="monetary_policy"),
    path('category/open_bank_account',
         views.open_bank_account, name="open_bank_account"),
    path('category/stock_market', views.stock_market, name="stock_market"),
    path('category/financial_consulting',
         views.financial_consulting, name="financial_consulting"),
    path('category/reservation', views.reservation, name="reservation"),
    path('category/promotion', views.promotion, name="promotion"),
    path('category/choose_bank', views.choose_bank, name="choose_bank"),
    path('category/become_VIP', views.become_VIP, name="become_VIP"),
    path('category/recipe_VIP/<str:type>', views.recipe_VIP, name="recipe_VIP"),
    path('category/send_consulting/',
         views.send_consulting, name="send_consulting"),
    path('set_reservation/', views.set_reservation, name='set_reservation'),
    path('choose_correct_bank/', views.choose_correct_bank,
         name='choose_correct_bank'),
    path('set_service/', views.set_service, name='set_service'),
    path('category/new_services/', views.new_services, name='new_services'),
    path('terms_of_use', views.terms_of_use, name='terms_of_use'),
]
